In [3]:
import numpy as np

### 对于ndarray结构来说,里面所有的元素必须是同一类型的,如果不是的话,会自动的进行向下转换

In [22]:
tang_list = [1,2,3,4, 5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

### ndarray attribute

In [12]:
type(tang_array)

numpy.ndarray

In [13]:
tang_array.dtype

dtype('int64')

In [14]:
tang_array.itemsize

8

In [15]:
tang_array.shape

(5,)

In [16]:
tang_array.size

5

In [17]:
np.size(tang_array)

5

In [18]:
np.shape(tang_array)

(5,)

In [19]:
tang_array.ndim

1

In [20]:
tang_array

array([1, 2, 3, 4, 5])

In [21]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

### 索引与切片,跟Python都是一样的

In [23]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

1

In [24]:
tang_array[1:3]

array([2, 3])

In [25]:
tang_array[-2:]

array([4, 5])

### 矩阵格式(多维形式)

In [27]:
tang_array = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
tang_array.shape

(3, 3)

In [29]:
tang_array.size

9

In [30]:
tang_array.ndim

2

In [31]:
tang_array[1,1]

5

In [32]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [33]:
tang_array[1]

array([ 4, 10,  6])

In [34]:
tang_array[:, 1]

array([ 2, 10,  8])

In [35]:
tang_array[0, 0:2]

array([1, 2])

In [36]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [37]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [39]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [40]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [41]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [42]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [43]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [44]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
mask = np.array([0,0,0,1,1,1,0,0,1,1], dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [47]:
tang_array[mask]

array([30, 40, 50, 80, 90])

In [56]:
random_array = np.random.rand(10)
random_array

array([0.09671239, 0.7303451 , 0.75581462, 0.58025548, 0.42992342,
       0.72927439, 0.94325007, 0.15079801, 0.70625901, 0.46317569])

In [57]:
mask = random_array > 0.5
mask

array([False,  True,  True,  True, False,  True,  True, False,  True,
       False])

In [58]:
tang_array[mask]

array([10, 20, 30, 50, 60, 80])

In [61]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [62]:
np.where(tang_array > 30)

(array([3, 4]),)

In [63]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [10]:
tang_array = np.array([1,2,3,4,5], dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [11]:
tang_array.dtype

dtype('float32')

In [12]:
tang_array.nbytes

20

In [14]:
tang_array = np.array([1,10,3,5,'str'], dtype=object)
tang_array

array([1, 10, 3, 5, 'str'], dtype=object)

In [15]:
tang_array * 2

array([2, 20, 6, 10, 'strstr'], dtype=object)

In [20]:
tang_array = np.array([1,2,3,4,5])
tang_array2 = np.asarray(tang_array, dtype=np.float32)

In [21]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [22]:
tang_array

array([1, 2, 3, 4, 5])

In [23]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [24]:
tang_array

array([1, 2, 3, 4, 5])