In [1]:
import numpy as np

### 对于ndarray结构来说,里面所有的元素必须是同一类型的,如果不是的话,会自动的进行向下转换

In [22]:
tang_list = [1,2,3,4, 5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

### ndarray attribute

In [12]:
type(tang_array)

numpy.ndarray

In [13]:
tang_array.dtype

dtype('int64')

In [14]:
tang_array.itemsize

8

In [15]:
tang_array.shape

(5,)

In [16]:
tang_array.size

5

In [17]:
np.size(tang_array)

5

In [18]:
np.shape(tang_array)

(5,)

In [19]:
tang_array.ndim

1

In [20]:
tang_array

array([1, 2, 3, 4, 5])

In [21]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

### 索引与切片,跟Python都是一样的

In [23]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

1

In [24]:
tang_array[1:3]

array([2, 3])

In [25]:
tang_array[-2:]

array([4, 5])