### 四则运算

In [1]:
import numpy as np

In [2]:
x = np.array([5,5])
y = np.array([2,2])

In [3]:
np.multiply(x,y)

array([10, 10])

In [4]:
np.dot(x,y)

20

In [5]:
x.shape

(2,)

In [6]:
y.shape

(2,)

In [7]:
x.shape = 2,1
x

array([[5],
       [5]])

In [8]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [9]:
y.shape = 1,2
y

array([[2, 2]])

In [11]:
x

array([[5],
       [5]])

In [12]:
print(x.shape)
print(y.shape)

(2, 1)
(1, 2)


In [10]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [13]:
np.dot(y,x)

array([[20]])

In [14]:
x=np.array([1,1,1])
y=np.array([[1,2,3],[4,5,6]])
print(x * y)

[[1 2 3]
 [4 5 6]]


In [18]:
x=np.array([1,1,1,4])

In [21]:
y=np.array([1,1,1,2])

In [22]:
x==y

array([ True,  True,  True, False])

In [25]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [26]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [27]:
np.logical_not(x,y)

array([0, 0, 0, 0])