### 文件读写

In [ ]:
import numpy as np

使用numpy读取数据

In [2]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing tang.txt


In [4]:
data = []
with open('tang.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [6]:
data = np.loadtxt('tang.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [8]:
%%writefile tang2.txt
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [9]:
data = np.loadtxt('tang2.txt', delimiter=',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [10]:
%%writefile tang2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [12]:
data = np.loadtxt('tang2.txt', delimiter=',', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

* 'tang2.txt':路径最好放到和代码一起
* skiprows:去掉几行
* delimiter=',':分割符
* usecols = (0,1,4):指定使用哪几列

In [15]:
tang_array = np.array([[1,2,3],[4,5,6]])

In [16]:
np.savetxt('tang4.txt', tang_array)

In [19]:
np.savetxt('tang4.txt', tang_array, fmt='%d')

In [20]:
np.savetxt('tang4.txt', tang_array, fmt='%d', delimiter=',')

In [21]:
np.savetxt('tang4.txt', tang_array, fmt='%2f', delimiter=',')

读写array结构

In [22]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy', tang_array)

In [23]:
tang = np.load('tang_array.npy')
tang

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
tang_array2 = np.arange(10)
tang_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.savez('tang.npz', a=tang_array, b=tang_array2)

In [27]:
data = np.load('tang.npz')

In [30]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x7f9852362e10>)

In [31]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])