### Numpy练习题

打印当前Numpy版本

In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.15.4


构造一个全零的矩阵,并打印其占用的内存大小

In [9]:
z = np.zeros((5,5))
print('%d bytes' % (z.size * z.itemsize))

200 bytes


打印函数的帮助文档,比如numpy.add

In [11]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

创建一个10-49的数组,并将其倒序排序

In [12]:
tang_array = np.arange(10,50,1)
tang_array = tang_array[::-1]

tang_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组当中不为0的索引

In [15]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10]),)

随机构造一个3*3的矩阵,并打印其中最大最小值

In [18]:
tang_array = np.random.random((3,3))
tang_array.max()
tang_array.min()

0.035091939163851116

构建一个5*5的矩阵,令其值都为1,并在最外层加上一圈0

In [3]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array, pad_width=1, mode='constant', constant_values=0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
# print(help(np.pad))

构建一个shape为(6,7,8)的矩阵,并找到第100个元素的索引值

In [6]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

对一个5*5的矩阵做归一化操作

In [8]:
tang_array = np.random.random((5,5))
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array - tang_min)/(tang_max - tang_min)
tang_array

array([[0.32975366, 0.27036887, 0.17031845, 0.0030434 , 0.        ],
       [0.93289599, 0.86137187, 0.80977635, 0.20883962, 0.21445214],
       [0.85299511, 0.05867124, 0.32996666, 0.94127497, 1.        ],
       [0.19103485, 0.39103713, 0.99367402, 0.3164087 , 0.59425898],
       [0.46131983, 0.74552367, 0.75643786, 0.24771344, 0.21341215]])

找到两个数组中相同的值

In [11]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1)
print(z2)
# print(np.intersectld(z1,z2))

[1 4 3 3 5 3 0 1 2 5]
[1 7 2 4 0 3 7 9 6 2]


得到今天 明天 昨天的日期

In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

In [14]:
yesterday

numpy.datetime64('2018-12-12')

In [15]:
today

numpy.datetime64('2018-12-13')

In [16]:
tomorrow

numpy.datetime64('2018-12-12')

得到一个月中所有的天

In [17]:
np.arange('2017-10', '2017-11', dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

得到一个数的整数部分

In [18]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([0., 3., 3., 7., 0., 4., 7., 2., 8., 0.])

构造一个是数组,让它不能被改变

In [19]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

打印大数据的部分值,全部值

In [21]:
z = np.zeros((15,15))
np.set_printoptions(threshold=5)
z
np.set_printoptions(threshold=np.nan)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.