### Python科学计算库Numpy

In [4]:
import numpy as np

In [10]:
array = np.array([1,2,3,4,5])
print(type(array))

<class 'numpy.ndarray'>


In [12]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [13]:
 array2 + array

array([ 3,  5,  7,  9, 11])

In [14]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [15]:
array[0]

1

In [16]:
array[3]

4

In [19]:
array.shape

(5,)

In [20]:
tang_list = [1,2,3,4,5]
tang_list.shape

AttributeError: 'list' object has no attribute 'shape'

In [21]:
np.array([[1,2,3],
         [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])