### 随机模块

In [2]:
import numpy as np
# 所有值都是从0到1
np.random.rand(3,2)

array([[0.17278955, 0.24526968],
       [0.34484161, 0.50016063],
       [0.16615608, 0.48209217]])

In [5]:
# 返回的是随机的整数,左闭右开
np.random.randint(10,size=(5,4))

array([[3, 9, 5, 9],
       [4, 1, 3, 2],
       [2, 4, 6, 1],
       [1, 2, 6, 8],
       [5, 3, 8, 8]])

In [6]:
np.random.rand()

0.4396716336571105

In [7]:
np.random.random_sample()

0.6805077578334637

In [9]:
np.random.randint(0,10,3)

array([5, 8, 1])

In [17]:
x=np.array([1,1,1])

In [22]:
np.set_printoptions(precision=2)

In [23]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.12, -0.17, -0.07,  0.03,  0.21,  0.01, -0.07, -0.02, -0.03,
        0.1 ])

洗牌

In [25]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.shuffle(tang_array)

In [34]:
tang_array

array([2, 5, 1, 0, 7, 6, 3, 9, 8, 4])

随机的种子

In [53]:
np.random.seed(0)

In [54]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.18,  0.04,  0.1 ,  0.22,  0.19, -0.1 ,  0.1 , -0.02, -0.01,
        0.04])