### 文件读写

In [ ]:
import numpy as np

使用numpy读取数据

In [2]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing tang.txt


In [4]:
data = []
with open('tang.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [6]:
data = np.loadtxt('tang.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [8]:
%%writefile tang2.txt
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [9]:
data = np.loadtxt('tang2.txt', delimiter=',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [10]:
%%writefile tang2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [12]:
data = np.loadtxt('tang2.txt', delimiter=',', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

* 'tang2.txt':路径最好放到和代码一起
* skiprows:去掉几行
* delimiter=',':分割符
* usecols = (0,1,4):指定使用哪几列